spring.application.name=demo
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d7q3i0rbc2fs73amjf3g-a.oregon-postgres.render.com:5432/spring_demo_db_fde9
spring.datasource.username=spring_demo_db_fde9_user
spring.datasource.password=G0ajb8XEWhwrdtPgwAztiXqNOWbfFWds

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.boot=DEBUG